name: cis17b_shopping_cart_final

services:
  app:
    build: .
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    network_mode: host

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: "catalog"
      MARIADB_USER: "admin"
      MARIADB_PASSWORD: "password"

  adminer:
    image: adminer
    ports:
      - 8080:8080
